# Generated by Django 4.2.28 on 2026-04-26 13:11

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=200, unique=True)),
                ('public_own', models.IntegerField(blank=True, null=True)),
                ('public_holding', models.IntegerField(blank=True, null=True)),
                ('holding_name', models.CharField(blank=True, max_length=500, null=True)),
                ('ticket_own', models.CharField(blank=True, max_length=50, null=True)),
                ('ticket_holding', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200, unique=True)),
                ('country_code', models.CharField(default='de', max_length=200)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siapp.continent')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(db_comment='Name of the customer company', max_length=200, unique=True, verbose_name='Customer name')),
            ],
        ),
        migrations.CreateModel(
            name='GeoCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=120)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('capital', models.BooleanField()),
                ('state', models.CharField(max_length=120, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siapp.country')),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_customer_id', to='siapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_cluster_name', models.CharField(max_length=200, unique=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_cluster_customer_id', to='siapp.customer')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siapp.industry')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrademarkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trademark_group_name', models.CharField(max_length=200, unique=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trademark_group_customer_id', to='siapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='SysLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResetPasswordToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(auto_created=True, db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('token', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegionValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_margin', models.FloatField(blank=True, null=True)),
                ('profit_margin_real_value_status', models.BooleanField(default=False)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siapp.industry')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siapp.region')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_group_name', models.CharField(max_length=200, unique=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_group_customer_id', to='siapp.customer')),
                ('product_cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siapp.productcluster')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_description_name', models.CharField(max_length=200, unique=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_description_customer_id', to='siapp.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siapp.product')),
                ('trademark_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_description_trademark_group', to='siapp.trademarkgroup')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siapp.productgroup'),
        ),
        migrations.CreateModel(
            name='OtpSecrets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPlants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_plant_name', models.CharField(db_comment='Name of the Customer Plant', max_length=200, verbose_name='Customer Plant name')),
                ('postalcode', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(db_comment='Address of the customer plant', max_length=200, null=True, verbose_name='Address of the customer plant')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siapp.geocoordinates')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField(db_comment='Date the period begins on', verbose_name='Begin Date')),
                ('end', models.DateField(db_comment='Date the period ends on', verbose_name='End Date')),
                ('name', models.CharField(db_comment='name given by the Customer to this date period for identification', max_length=200, verbose_name='date period name')),
                ('customer', models.ForeignKey(db_comment='Customer using this date period', on_delete=django.db.models.deletion.CASCADE, to='siapp.customer', verbose_name='Customer')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siapp.year')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='headquarter_address',
            field=models.ForeignKey(blank=True, db_comment='Address of the customer company, without country', null=True, on_delete=django.db.models.deletion.SET_NULL, to='siapp.geocoordinates', verbose_name="Customer's address"),
        ),
        migrations.AddField(
            model_name='customer',
            name='headquarter_country',
            field=models.ForeignKey(blank=True, db_comment='Country the customer company resides in', null=True, on_delete=django.db.models.deletion.SET_NULL, to='siapp.country', verbose_name="Customer's country"),
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siapp.region'),
        ),
        migrations.CreateModel(
            name='BuyerPlants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_plant_name', models.CharField(db_comment='Name of the Buyer Plant', max_length=200, verbose_name='Buyer Plant name')),
                ('postalcode', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(db_comment='Address of the customer', max_length=200, null=True, verbose_name='Address of the customer')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siapp.buyer')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siapp.geocoordinates')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='allowed_product_clusters',
            field=models.ManyToManyField(blank=True, related_name='allowed_users', to='siapp.productcluster'),
        ),
        migrations.AddField(
            model_name='user',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='siapp.customer'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='ItemsToCustomerPeriods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('spend', models.BigIntegerField()),
                ('quantity', models.FloatField()),
                ('fault_ppm', models.IntegerField(blank=True, null=True)),
                ('granted_discount', models.FloatField(blank=True, null=True)),
                ('address_buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_buyer', to='siapp.geocoordinates')),
                ('address_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_customer', to='siapp.geocoordinates')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siapp.buyer')),
                ('buyer_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siapp.buyerplants')),
                ('country_buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_buyer_id', to='siapp.country')),
                ('country_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_customer_id', to='siapp.country')),
                ('customerperiod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siapp.customerperiod')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siapp.product')),
                ('product_cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siapp.productcluster')),
                ('product_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siapp.productdescription')),
                ('product_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siapp.productgroup')),
            ],
            options={
                'indexes': [models.Index(fields=['product_group_id', 'country_customer_id'], name='idx_prod_group_count_cust'), models.Index(fields=['buyer_id', 'country_buyer_id'], name='idx_buy_count_buy'), models.Index(fields=['product_id', 'product_group_id', 'buyer_id', 'country_buyer_id', 'country_customer_id'], name='idx_prod_grp_by_cot_by_cnt_cst'), models.Index(fields=['buyer_id', 'address_customer', 'address_buyer'], name='idx_buy_add_cust_add_buy')],
            },
        ),
    ]
