# Generated by Django 4.2.28 on 2026-06-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='salesforce_account_id',
            field=models.CharField(blank=True, db_index=True, max_length=18, null=True),
        ),
    ]
